extends RefCounted
## ÜRETİLDİ — elle düzenleme. Yeniden yazmak için (proto klasöründen):
##   python tools/uretec.py <deneme> <tohum>
## Harita harfleri levels.gd ile aynı.

const ALL := [
	{"yon": "R", "zorluk": 0.00, "sinif": "kolay", "map": [
		# solution_toggles=1 · solution_reflections=4 · relevant_mirrors=2 · irrelevant_mirrors=0 · expanded_states=2 · max_backtrack=1 · near_misses=1 · beam_crossings=0 · aha=False
		".......",
		".......",
		".......",
		".......",
		".......",
		".......",
		".......",
		"..s..T.",
		"..N..M.",
		"..F..s.",
		".......",
		".......",
	]},
	{"yon": "L", "zorluk": 0.17, "sinif": "kolay", "map": [
		# solution_toggles=1 · solution_reflections=6 · relevant_mirrors=3 · irrelevant_mirrors=0 · expanded_states=4 · max_backtrack=2 · near_misses=1 · beam_crossings=0 · aha=False
		".......",
		".......",
		".T.N...",
		".N.s...",
		".......",
		".b.b...",
		".......",
		"...M.F.",
		".......",
		".......",
		".......",
		"...M...",
	]},
	{"yon": "U", "zorluk": 0.27, "sinif": "kolay", "map": [
		# solution_toggles=3 · solution_reflections=6 · relevant_mirrors=3 · irrelevant_mirrors=0 · expanded_states=3 · max_backtrack=1 · near_misses=1 · beam_crossings=0 · aha=True
		".......",
		".......",
		".......",
		".......",
		".......",
		"s....N.",
		"......T",
		".......",
		".....F.",
		".......",
		"b....N.",
		".....bM",
	]},
	{"yon": "L", "zorluk": 0.27, "sinif": "orta", "map": [
		# solution_toggles=3 · solution_reflections=5 · relevant_mirrors=5 · irrelevant_mirrors=0 · expanded_states=7 · max_backtrack=2 · near_misses=1 · beam_crossings=1 · aha=False
		".......",
		".......",
		".......",
		".......",
		"..M..F.",
		"N......",
		".......",
		"M..N...",
		".......",
		"TRMN...",
		".......",
		"...M...",
	]},
	{"yon": "U", "zorluk": 0.33, "sinif": "orta", "map": [
		# solution_toggles=3 · solution_reflections=7 · relevant_mirrors=4 · irrelevant_mirrors=1 · expanded_states=4 · max_backtrack=1 · near_misses=1 · beam_crossings=1 · aha=True
		".......",
		".......",
		".......",
		".......",
		".......",
		".......",
		"...N.b.",
		"M....s.",
		".......",
		"..sM.RM",
		"..N...T",
		"F......",
	]},
	{"yon": "U", "zorluk": 0.39, "sinif": "orta", "map": [
		# solution_toggles=5 · solution_reflections=6 · relevant_mirrors=5 · irrelevant_mirrors=0 · expanded_states=7 · max_backtrack=3 · near_misses=1 · beam_crossings=2 · aha=False
		"N..M...",
		"..T.sN.",
		".......",
		"M....M.",
		".......",
		".......",
		"N.M.F..",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "L", "zorluk": 0.42, "sinif": "orta", "map": [
		# solution_toggles=4 · solution_reflections=6 · relevant_mirrors=5 · irrelevant_mirrors=0 · expanded_states=6 · max_backtrack=2 · near_misses=1 · beam_crossings=0 · aha=True
		"..M...F",
		"....M.T",
		".MN....",
		".......",
		".......",
		".b..M..",
		".......",
		".......",
		".......",
		"....M..",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.73, "sinif": "zor", "map": [
		# solution_toggles=6 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=11 · max_backtrack=3 · near_misses=2 · beam_crossings=1 · aha=True
		".......",
		".......",
		".......",
		".......",
		".......",
		"..TN...",
		"..N.R.M",
		"...N.b.",
		".......",
		".FM.N.N",
		"..M..M.",
		".M..M..",
	]},
	{"yon": "R", "zorluk": 0.87, "sinif": "zor", "map": [
		# solution_toggles=9 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=15 · max_backtrack=5 · near_misses=1 · beam_crossings=0 · aha=True
		"MN.....",
		".......",
		".N...N.",
		".......",
		".....T.",
		"N..N..M",
		"....F.N",
		"M......",
		".......",
		"...N..M",
		".......",
		".......",
	]},
	{"yon": "U", "zorluk": 1.00, "sinif": "zor", "map": [
		# solution_toggles=6 · solution_reflections=7 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=25 · max_backtrack=9 · near_misses=2 · beam_crossings=0 · aha=True
		".......",
		".......",
		".N....N",
		".......",
		"N...N..",
		".......",
		"NN..N.N",
		".......",
		".......",
		"R......",
		"TM..N.F",
		".......",
	]},
]
