extends RefCounted
## ÜRETİLDİ — elle düzenleme. Yeniden yazmak için (proto klasöründen):
##   python tools/uretec.py 40000 1 is4
## Harita harfleri levels.gd ile aynı.

const ALL := [
	{"yon": "U", "zorluk": 0.83, "sinif": "bölücüsüz", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=20 · max_backtrack=9 · near_misses=2 · beam_crossings=0 · aha=True
		"T....NMM",
		"R...N...",
		"M....MF.",
		"....M..M",
		".....N..",
		"........",
		"........",
		"N...M...",
		"........",
		".......M",
		"........",
		"........",
		"........",
		"........",
	]},
	{"yon": "D", "zorluk": 0.85, "sinif": "bölücüsüz", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=24 · max_backtrack=9 · near_misses=2 · beam_crossings=1 · aha=True
		"........",
		"........",
		"........",
		"........",
		"........",
		"........",
		"....M...",
		".....F..",
		"........",
		"M.N.MM.N",
		".....R..",
		"..N....M",
		".....T.M",
		"N...M...",
	]},
	{"yon": "L", "zorluk": 0.85, "sinif": "bölücüsüz", "map": [
		# solution_toggles=9 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=19 · max_backtrack=9 · near_misses=2 · beam_crossings=1 · aha=True
		"........",
		"........",
		"........",
		"........",
		"........",
		"........",
		"M..F...T",
		".M...N..",
		".N....N.",
		"........",
		"N....M..",
		"......NM",
		"........",
		".....M.N",
	]},
	{"yon": "D", "zorluk": 0.87, "sinif": "bölücüsüz", "map": [
		# solution_toggles=9 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=22 · max_backtrack=9 · near_misses=2 · beam_crossings=0 · aha=True
		"........",
		"........",
		"M.M..T..",
		".....R..",
		"........",
		"........",
		"........",
		"..N.N...",
		"M...M...",
		".F......",
		"....MN..",
		"........",
		".N...N..",
		"N....M..",
	]},
	{"yon": "D", "zorluk": 0.93, "sinif": "bölücülü", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=59 · max_backtrack=8 · near_misses=3 · beam_crossings=0 · aha=True
		"........",
		"........",
		"........",
		"........",
		"........",
		"........",
		"..TN..M.",
		"....T..N",
		"M..M.N.M",
		"...F...N",
		"........",
		"........",
		"...b.Y..",
		"N....M.N",
	]},
	{"yon": "R", "zorluk": 0.95, "sinif": "bölücülü", "map": [
		# solution_toggles=9 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=61 · max_backtrack=7 · near_misses=3 · beam_crossings=0 · aha=True
		"MN.N....",
		"T.......",
		"........",
		".NY...N.",
		"F.M..N..",
		".MN.....",
		"..TN....",
		".N....M.",
		"........",
		"........",
		"........",
		"........",
		"........",
		"........",
	]},
	{"yon": "R", "zorluk": 0.98, "sinif": "bölücülü", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=59 · max_backtrack=9 · near_misses=3 · beam_crossings=1 · aha=True
		"........",
		"........",
		"........",
		"........",
		"........",
		"T.......",
		"........",
		".M....N.",
		"NMM..YM.",
		"........",
		"........",
		"M.M...N.",
		"...F.M..",
		"......T.",
	]},
	{"yon": "D", "zorluk": 1.00, "sinif": "bölücülü", "map": [
		# solution_toggles=8 · solution_reflections=8 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=82 · max_backtrack=10 · near_misses=3 · beam_crossings=0 · aha=True
		"........",
		"....TNMF",
		"........",
		"........",
		".M...MMM",
		".N....YN",
		"........",
		"........",
		".N...M..",
		"........",
		"..T....M",
		"........",
		"........",
		"........",
	]},
]
