extends RefCounted
## ÜRETİLDİ — elle düzenleme. Yeniden yazmak için (proto klasöründen):
##   python tools/uretec.py 20000 11 is11
## Harita harfleri levels.gd ile aynı.

const ALL := [
	{"yon": "D", "zorluk": 0.35, "sinif": "orta", "map": [
		# solution_toggles=3 · solution_reflections=7 · relevant_mirrors=6 · irrelevant_mirrors=0 · expanded_states=7 · max_backtrack=2 · near_misses=1 · beam_crossings=0 · aha=True
		"....F..",
		".......",
		".....NT",
		".M..N..",
		".......",
		"N...NM.",
		".......",
		".......",
		".N..s..",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.39, "sinif": "orta", "map": [
		# solution_toggles=7 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=8 · max_backtrack=2 · near_misses=1 · beam_crossings=0 · aha=False
		".....F.",
		".......",
		".......",
		"...M.M.",
		".......",
		".sN....",
		"..NM...",
		"...T...",
		".N.M...",
		".......",
		".......",
		"..M....",
	]},
	{"yon": "D", "zorluk": 0.44, "sinif": "orta", "map": [
		# solution_toggles=6 · solution_reflections=8 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=13 · max_backtrack=3 · near_misses=1 · beam_crossings=0 · aha=False
		"....F..",
		".......",
		".M...M.",
		".......",
		"..M.N.N",
		".......",
		".......",
		"...NNMM",
		"...T...",
		".......",
		".......",
		"....MM.",
	]},
	{"yon": "D", "zorluk": 0.48, "sinif": "orta", "map": [
		# solution_toggles=6 · solution_reflections=7 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=22 · max_backtrack=4 · near_misses=1 · beam_crossings=0 · aha=False
		"....F..",
		"..NN...",
		"...YM.M",
		"..T....",
		".......",
		".......",
		"N..NN..",
		".......",
		".......",
		".......",
		"....NN.",
		".....T.",
	]},
	{"yon": "D", "zorluk": 0.53, "sinif": "orta", "map": [
		# solution_toggles=5 · solution_reflections=6 · relevant_mirrors=6 · irrelevant_mirrors=0 · expanded_states=21 · max_backtrack=4 · near_misses=3 · beam_crossings=0 · aha=False
		"..F....",
		".......",
		".......",
		"...M..N",
		"N.NY...",
		".......",
		"..R....",
		"M..M.N.",
		"M.T...T",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.57, "sinif": "orta", "map": [
		# solution_toggles=7 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=10 · max_backtrack=4 · near_misses=1 · beam_crossings=1 · aha=True
		"sNF....",
		".......",
		"N.M....",
		".......",
		"MM.....",
		"....T..",
		".......",
		"N...M..",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.62, "sinif": "orta", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=26 · max_backtrack=4 · near_misses=1 · beam_crossings=1 · aha=False
		".MYN.F.",
		".......",
		"..N..M.",
		"TM.NM..",
		".....M.",
		".N.....",
		".......",
		".......",
		"....NN.",
		".......",
		".......",
		".....T.",
	]},
	{"yon": "D", "zorluk": 0.66, "sinif": "orta", "map": [
		# solution_toggles=6 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=25 · max_backtrack=5 · near_misses=3 · beam_crossings=0 · aha=False
		".F..N..",
		".......",
		"..M.N..",
		"....T..",
		".....M.",
		"sM.....",
		".......",
		"N.Y....",
		".......",
		"M.M..N.",
		"M.T....",
		".......",
	]},
	{"yon": "D", "zorluk": 0.70, "sinif": "orta", "map": [
		# solution_toggles=7 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=30 · max_backtrack=5 · near_misses=1 · beam_crossings=0 · aha=True
		".sT..F.",
		".NN...N",
		".......",
		".......",
		"..Y..M.",
		".......",
		"...T...",
		".......",
		".......",
		"M.M...N",
		"N..M...",
		".......",
	]},
	{"yon": "D", "zorluk": 0.75, "sinif": "orta", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=26 · max_backtrack=6 · near_misses=3 · beam_crossings=0 · aha=False
		".F.....",
		".......",
		".......",
		"MM..N.M",
		".MT....",
		".b...N.",
		"N....Y.",
		"....Ms.",
		".......",
		".......",
		"......N",
		"....NT.",
	]},
	{"yon": "D", "zorluk": 0.87, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=8 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=31 · max_backtrack=7 · near_misses=3 · beam_crossings=0 · aha=True
		"NN.MF..",
		".......",
		".Y..MN.",
		".N..N..",
		"....T..",
		"NN.....",
		".......",
		".N...T.",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.87, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=24 · max_backtrack=8 · near_misses=2 · beam_crossings=1 · aha=True
		".F.....",
		"....T..",
		"MM.M...",
		".......",
		".......",
		"N..N...",
		"M...M..",
		"N..Y..N",
		".T....s",
		".......",
		".......",
		".N..N..",
	]},
	{"yon": "D", "zorluk": 0.88, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=42 · max_backtrack=7 · near_misses=2 · beam_crossings=0 · aha=True
		".F...T.",
		"....MN.",
		".......",
		"M.M.MT.",
		".NY....",
		".......",
		"M.M....",
		"M....M.",
		".......",
		"..N....",
		".....N.",
		".......",
	]},
	{"yon": "D", "zorluk": 0.88, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=20 · max_backtrack=8 · near_misses=3 · beam_crossings=1 · aha=True
		"N..F.MN",
		"....MM.",
		"M...N..",
		"N..M.N.",
		"...R...",
		"...T..N",
		".......",
		".......",
		".......",
		".......",
		"N......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.89, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=38 · max_backtrack=7 · near_misses=3 · beam_crossings=0 · aha=True
		".M.FMT.",
		"....N.N",
		".MNN..Y",
		".TN...s",
		".......",
		".......",
		"..N....",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.89, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=28 · max_backtrack=8 · near_misses=2 · beam_crossings=0 · aha=True
		"..F....",
		"MN..M..",
		"T......",
		"MM.M...",
		".MM.M..",
		".......",
		".......",
		".......",
		"YM..T..",
		".......",
		"b...M..",
		".......",
	]},
	{"yon": "D", "zorluk": 0.89, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=17 · max_backtrack=9 · near_misses=3 · beam_crossings=1 · aha=True
		"..F....",
		".......",
		".N.MT..",
		"....R..",
		".......",
		".NsNN..",
		".N...N.",
		".......",
		"....NM.",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.90, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=33 · max_backtrack=6 · near_misses=3 · beam_crossings=0 · aha=True
		"T..F.MT",
		"NN...NN",
		"M..N.N.",
		".......",
		".......",
		".......",
		".N...Ys",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.96, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=27 · max_backtrack=9 · near_misses=3 · beam_crossings=1 · aha=True
		".....F.",
		"MN.....",
		"...TMNN",
		".......",
		".N....M",
		".......",
		"N...M.N",
		".......",
		".......",
		".M.....",
		"M......",
		".......",
	]},
	{"yon": "D", "zorluk": 1.00, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=51 · max_backtrack=8 · near_misses=3 · beam_crossings=1 · aha=True
		"M.MF...",
		".N.....",
		"Y..M...",
		".......",
		"NNN...T",
		".......",
		".......",
		"N......",
		".......",
		"MM.....",
		"N.T....",
		".......",
	]},
]
