extends RefCounted
## ÜRETİLDİ — elle düzenleme. Yeniden yazmak için (proto klasöründen):
##   python tools/uretec.py 40000 1 is4
## Harita harfleri levels.gd ile aynı.

const ALL := [
	{"yon": "L", "zorluk": 0.87, "sinif": "bölücüsüz", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=26 · max_backtrack=9 · near_misses=2 · beam_crossings=0 · aha=True
		".......M",
		"........",
		"........",
		"........",
		"........",
		"........",
		"...M...N",
		"........",
		"........",
		".....M.N",
		"s..M...N",
		"........",
		"...N.N.N",
		"N....F.T",
	]},
	{"yon": "U", "zorluk": 0.88, "sinif": "bölücüsüz", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=20 · max_backtrack=9 · near_misses=2 · beam_crossings=0 · aha=True
		"T....NMM",
		"R...N...",
		"M....MF.",
		"....M..M",
		".....N..",
		"........",
		"........",
		"N...M...",
		"........",
		".......M",
		"........",
		"........",
		"........",
		"........",
	]},
	{"yon": "D", "zorluk": 0.92, "sinif": "bölücüsüz", "map": [
		# solution_toggles=9 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=22 · max_backtrack=9 · near_misses=2 · beam_crossings=0 · aha=True
		"........",
		"........",
		"M.M..T..",
		".....R..",
		"........",
		"........",
		"........",
		"..N.N...",
		"M...M...",
		".F......",
		"....MN..",
		"........",
		".N...N..",
		"N....M..",
	]},
	{"yon": "U", "zorluk": 0.93, "sinif": "bölücülü", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=1 · expanded_states=45 · max_backtrack=7 · near_misses=3 · beam_crossings=2 · aha=True
		"M.......",
		"........",
		"........",
		"........",
		"........",
		"MN...N..",
		"........",
		"........",
		".Yb.....",
		".....R..",
		"M...NM..",
		"MM......",
		"NTF.....",
		"....N..T",
	]},
	{"yon": "U", "zorluk": 0.95, "sinif": "bölücüsüz", "map": [
		# solution_toggles=9 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=24 · max_backtrack=8 · near_misses=3 · beam_crossings=0 · aha=True
		"...N....",
		".N.MN...",
		"M..M....",
		".M..M.M.",
		".N.N....",
		"F.......",
		"........",
		"........",
		"........",
		"...N.T..",
		"........",
		"........",
		"........",
		"........",
	]},
	{"yon": "U", "zorluk": 0.98, "sinif": "bölücülü", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=43 · max_backtrack=8 · near_misses=3 · beam_crossings=0 · aha=True
		"...M...N",
		"......sY",
		"........",
		".M.NT...",
		"......F.",
		"......MM",
		"........",
		"...M..M.",
		"........",
		"........",
		"........",
		"..TM....",
		".N......",
		"........",
	]},
	{"yon": "R", "zorluk": 0.99, "sinif": "bölücülü", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=48 · max_backtrack=9 · near_misses=3 · beam_crossings=0 · aha=True
		"........",
		"...T.F.N",
		"........",
		"..N...N.",
		"...N.MMM",
		".....NYM",
		"........",
		"........",
		"..M....M",
		"........",
		"........",
		"..T.....",
		"......M.",
		"........",
	]},
	{"yon": "L", "zorluk": 1.00, "sinif": "bölücülü", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=54 · max_backtrack=9 · near_misses=3 · beam_crossings=2 · aha=True
		".T..N..N",
		"..T.....",
		"..N...M.",
		"....N..N",
		".N....Y.",
		".N...FNM",
		"..M.M...",
		"........",
		"........",
		"........",
		"........",
		"........",
		"........",
		"........",
	]},
]
