extends RefCounted
## ÜRETİLDİ — elle düzenleme. Yeniden yazmak için (proto klasöründen):
##   python tools/uretec.py 20000 11 is11
## Harita harfleri levels.gd ile aynı.

const ALL := [
	{"yon": "D", "zorluk": 0.38, "sinif": "orta", "map": [
		# solution_toggles=6 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=9 · max_backtrack=2 · near_misses=1 · beam_crossings=0 · aha=False
		".FN.N..",
		".....Mb",
		".NM.NMT",
		".......",
		".......",
		".......",
		".......",
		"..M....",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.38, "sinif": "orta", "map": [
		# solution_toggles=6 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=9 · max_backtrack=2 · near_misses=1 · beam_crossings=2 · aha=False
		".....F.",
		"...MM..",
		".......",
		"..M.s..",
		"..N..M.",
		".....T.",
		".N.N.M.",
		".......",
		".....N.",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.38, "sinif": "orta", "map": [
		# solution_toggles=5 · solution_reflections=8 · relevant_mirrors=5 · irrelevant_mirrors=0 · expanded_states=5 · max_backtrack=1 · near_misses=1 · beam_crossings=1 · aha=True
		"....FMN",
		"Mb.....",
		"....N.s",
		".T.....",
		".......",
		"b....M.",
		".......",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.38, "sinif": "orta", "map": [
		# solution_toggles=5 · solution_reflections=8 · relevant_mirrors=5 · irrelevant_mirrors=1 · expanded_states=5 · max_backtrack=1 · near_misses=1 · beam_crossings=1 · aha=True
		".....F.",
		".......",
		"M....s.",
		".......",
		".M.N.RN",
		".N....T",
		".......",
		"N..Y...",
		".......",
		"....T..",
		".......",
		"...bs..",
	]},
	{"yon": "D", "zorluk": 0.38, "sinif": "orta", "map": [
		# solution_toggles=5 · solution_reflections=8 · relevant_mirrors=6 · irrelevant_mirrors=0 · expanded_states=7 · max_backtrack=2 · near_misses=2 · beam_crossings=0 · aha=False
		"..F....",
		".......",
		".......",
		"M.N..N.",
		".......",
		"R......",
		"TR...NM",
		"b....N.",
		".....bM",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.38, "sinif": "orta", "map": [
		# solution_toggles=5 · solution_reflections=8 · relevant_mirrors=5 · irrelevant_mirrors=0 · expanded_states=7 · max_backtrack=2 · near_misses=2 · beam_crossings=1 · aha=False
		"..Fs..N",
		"s..M...",
		"NN.....",
		".......",
		".bM..MT",
		".......",
		".......",
		".......",
		".......",
		"...M...",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.39, "sinif": "orta", "map": [
		# solution_toggles=5 · solution_reflections=8 · relevant_mirrors=5 · irrelevant_mirrors=0 · expanded_states=8 · max_backtrack=2 · near_misses=2 · beam_crossings=0 · aha=False
		".M..F..",
		".......",
		".M..MN.",
		".......",
		".N..N..",
		"...Ms..",
		"....T..",
		".......",
		".......",
		".......",
		"...bs..",
		".......",
	]},
	{"yon": "D", "zorluk": 0.41, "sinif": "orta", "map": [
		# solution_toggles=5 · solution_reflections=7 · relevant_mirrors=5 · irrelevant_mirrors=1 · expanded_states=10 · max_backtrack=5 · near_misses=1 · beam_crossings=1 · aha=False
		".F...Mb",
		".......",
		".......",
		".N....Y",
		"....NT.",
		"....N..",
		"..s...M",
		".......",
		"..N.N..",
		".......",
		".......",
		"....T..",
	]},
	{"yon": "D", "zorluk": 0.50, "sinif": "orta", "map": [
		# solution_toggles=8 · solution_reflections=8 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=11 · max_backtrack=2 · near_misses=2 · beam_crossings=0 · aha=False
		"....F..",
		"M......",
		".M.....",
		".......",
		".......",
		".M..M.M",
		".......",
		".......",
		".....T.",
		"MM.....",
		".M...M.",
		"NM.....",
	]},
	{"yon": "D", "zorluk": 0.52, "sinif": "orta", "map": [
		# solution_toggles=6 · solution_reflections=7 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=18 · max_backtrack=4 · near_misses=2 · beam_crossings=0 · aha=False
		"M...NF.",
		"T......",
		"..N.YM.",
		".......",
		"..M.M..",
		".......",
		".......",
		".......",
		".......",
		"..N...M",
		"......T",
		".......",
	]},
	{"yon": "D", "zorluk": 0.87, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=8 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=31 · max_backtrack=7 · near_misses=3 · beam_crossings=0 · aha=True
		"NN.MF..",
		".......",
		".Y..MN.",
		".N..N..",
		"....T..",
		"NN.....",
		".......",
		".N...T.",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.87, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=24 · max_backtrack=8 · near_misses=2 · beam_crossings=1 · aha=True
		".F.....",
		"....T..",
		"MM.M...",
		".......",
		".......",
		"N..N...",
		"M...M..",
		"N..Y..N",
		".T....s",
		".......",
		".......",
		".N..N..",
	]},
	{"yon": "D", "zorluk": 0.88, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=42 · max_backtrack=7 · near_misses=2 · beam_crossings=0 · aha=True
		".F...T.",
		"....MN.",
		".......",
		"M.M.MT.",
		".NY....",
		".......",
		"M.M....",
		"M....M.",
		".......",
		"..N....",
		".....N.",
		".......",
	]},
	{"yon": "D", "zorluk": 0.88, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=20 · max_backtrack=8 · near_misses=3 · beam_crossings=1 · aha=True
		"N..F.MN",
		"....MM.",
		"M...N..",
		"N..M.N.",
		"...R...",
		"...T..N",
		".......",
		".......",
		".......",
		".......",
		"N......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.89, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=38 · max_backtrack=7 · near_misses=3 · beam_crossings=0 · aha=True
		".M.FMT.",
		"....N.N",
		".MNN..Y",
		".TN...s",
		".......",
		".......",
		"..N....",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.89, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=28 · max_backtrack=8 · near_misses=2 · beam_crossings=0 · aha=True
		"..F....",
		"MN..M..",
		"T......",
		"MM.M...",
		".MM.M..",
		".......",
		".......",
		".......",
		"YM..T..",
		".......",
		"b...M..",
		".......",
	]},
	{"yon": "D", "zorluk": 0.89, "sinif": "zor", "map": [
		# solution_toggles=7 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=17 · max_backtrack=9 · near_misses=3 · beam_crossings=1 · aha=True
		"..F....",
		".......",
		".N.MT..",
		"....R..",
		".......",
		".NsNN..",
		".N...N.",
		".......",
		"....NM.",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.90, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=8 · irrelevant_mirrors=0 · expanded_states=33 · max_backtrack=6 · near_misses=3 · beam_crossings=0 · aha=True
		"T..F.MT",
		"NN...NN",
		"M..N.N.",
		".......",
		".......",
		".......",
		".N...Ys",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.96, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=27 · max_backtrack=9 · near_misses=3 · beam_crossings=1 · aha=True
		".....F.",
		"MN.....",
		"...TMNN",
		".......",
		".N....M",
		".......",
		"N...M.N",
		".......",
		".......",
		".M.....",
		"M......",
		".......",
	]},
	{"yon": "D", "zorluk": 1.00, "sinif": "zor", "map": [
		# solution_toggles=8 · solution_reflections=9 · relevant_mirrors=9 · irrelevant_mirrors=0 · expanded_states=51 · max_backtrack=8 · near_misses=3 · beam_crossings=1 · aha=True
		"M.MF...",
		".N.....",
		"Y..M...",
		".......",
		"NNN...T",
		".......",
		".......",
		"N......",
		".......",
		"MM.....",
		"N.T....",
		".......",
	]},
]
