extends RefCounted
## ÜRETİLDİ — elle düzenleme. Yeniden yazmak için (proto klasöründen):
##   python tools/uretec.py <deneme> <tohum>
## Harita harfleri levels.gd ile aynı.

const ALL := [
	{"yon": "D", "zorluk": 0.00, "sinif": "kolay", "map": [
		# solution_toggles=1 · solution_reflections=4 · relevant_mirrors=3 · irrelevant_mirrors=0 · expanded_states=4 · max_backtrack=2 · near_misses=1 · beam_crossings=0 · aha=False
		"...F...",
		".......",
		".......",
		".N.M.N.",
		".......",
		".M....b",
		".......",
		"......T",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "U", "zorluk": 0.14, "sinif": "kolay", "map": [
		# solution_toggles=3 · solution_reflections=5 · relevant_mirrors=3 · irrelevant_mirrors=0 · expanded_states=4 · max_backtrack=2 · near_misses=1 · beam_crossings=1 · aha=False
		".......",
		".......",
		"....Tb.",
		"MN.M...",
		".......",
		"N....s.",
		".F.....",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "R", "zorluk": 0.19, "sinif": "kolay", "map": [
		# solution_toggles=3 · solution_reflections=4 · relevant_mirrors=4 · irrelevant_mirrors=0 · expanded_states=5 · max_backtrack=2 · near_misses=1 · beam_crossings=0 · aha=False
		".T...N.",
		"...M.N.",
		".......",
		".......",
		".....M.",
		".......",
		"F..M...",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "U", "zorluk": 0.19, "sinif": "orta", "map": [
		# solution_toggles=3 · solution_reflections=4 · relevant_mirrors=4 · irrelevant_mirrors=0 · expanded_states=5 · max_backtrack=2 · near_misses=1 · beam_crossings=0 · aha=False
		".......",
		".......",
		".......",
		".......",
		".......",
		".......",
		".......",
		"T......",
		".N..N.M",
		"NM.....",
		"....F..",
		".......",
	]},
	{"yon": "R", "zorluk": 0.32, "sinif": "orta", "map": [
		# solution_toggles=3 · solution_reflections=7 · relevant_mirrors=6 · irrelevant_mirrors=0 · expanded_states=6 · max_backtrack=1 · near_misses=1 · beam_crossings=0 · aha=False
		".M...N.",
		".......",
		".TR.Ns.",
		".......",
		".......",
		".......",
		".......",
		"..M.N..",
		".......",
		".......",
		".......",
		"F.N....",
	]},
	{"yon": "L", "zorluk": 0.38, "sinif": "orta", "map": [
		# solution_toggles=3 · solution_reflections=5 · relevant_mirrors=5 · irrelevant_mirrors=0 · expanded_states=7 · max_backtrack=2 · near_misses=1 · beam_crossings=1 · aha=False
		".......",
		".......",
		".......",
		".......",
		"..M..F.",
		"N......",
		".......",
		"M..M...",
		".......",
		"TRNN...",
		".......",
		"...M...",
	]},
	{"yon": "R", "zorluk": 0.42, "sinif": "orta", "map": [
		# solution_toggles=4 · solution_reflections=8 · relevant_mirrors=6 · irrelevant_mirrors=0 · expanded_states=6 · max_backtrack=1 · near_misses=1 · beam_crossings=1 · aha=False
		"F.N....",
		".......",
		".N..T..",
		"..MbR..",
		"...bN..",
		".......",
		".N..M..",
		".......",
		".......",
		".......",
		".......",
		".......",
	]},
	{"yon": "D", "zorluk": 0.70, "sinif": "zor", "map": [
		# solution_toggles=6 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=1 · expanded_states=7 · max_backtrack=1 · near_misses=1 · beam_crossings=2 · aha=True
		".......",
		".......",
		".......",
		".....MT",
		"F....R.",
		"....N.M",
		".......",
		".......",
		"N....N.",
		"....b.N",
		".......",
		".....NM",
	]},
	{"yon": "D", "zorluk": 0.76, "sinif": "zor", "map": [
		# solution_toggles=4 · solution_reflections=6 · relevant_mirrors=6 · irrelevant_mirrors=0 · expanded_states=8 · max_backtrack=2 · near_misses=2 · beam_crossings=1 · aha=True
		".......",
		".......",
		".......",
		"....F..",
		".T.....",
		"..M..M.",
		".......",
		"N...MM.",
		".NM....",
		".......",
		".......",
		".....N.",
	]},
	{"yon": "D", "zorluk": 1.00, "sinif": "zor", "map": [
		# solution_toggles=6 · solution_reflections=8 · relevant_mirrors=7 · irrelevant_mirrors=0 · expanded_states=9 · max_backtrack=2 · near_misses=2 · beam_crossings=1 · aha=True
		"sM...M.",
		"N...N..",
		".......",
		".......",
		".......",
		"MM.....",
		"....T..",
		".M.....",
		"...F...",
		".......",
		"N..M...",
		".......",
	]},
]
